### ISSUE TITLE
"attempt to concatenate local 'ext' (a nil value)"

### ISSUE THREAD

**Issue by trych** [karpathy/neuraltalk2#11] opened 2015-11-25 14:17 UTC
After I finally got it to work this morning, now there is an error again and it refuses to work. Here's what I get:

```
$ th eval.lua -model /Users/username/Documents/NeuralTalk2/checkpoint_v1.t7_cpu.t7 -image_folder /Users/username/Documents/NeuralTalk2/images -num_images -1 -gpuid -1
DataLoaderRaw loading images from folder:   /Users/username/Documents/NeuralTalk2/images  
listing all images in directory /Users/username/Documents/NeuralTalk2/images  
DataLoaderRaw found 21 images 
constructing clones inside the LanguageModel  
/Users/username/torch/install/bin/luajit: /Users/username/torch/install/share/lua/5.1/image/init.lua:337: attempt to concatenate local 'ext' (a nil value)
stack traceback:
  /Users/username/torch/install/share/lua/5.1/image/init.lua:337: in function 'load'
  ./misc/DataLoaderRaw.lua:74: in function 'getBatch'
  eval.lua:115: in function 'eval_split'
  eval.lua:169: in main chunk
  [C]: in function 'dofile'
  ...username/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
  [C]: at 0x010bdd1f10
```

The strange thing (at least to me) is that it claims it finds 21 images, when there is actually only 20 in the images folder. Andybody knows what's wrong here?

**Comment by fmassa** [comment] 2015-11-25 14:50
I think one of your images doesn't have an extension. Could you check ?

**Comment by fmassa** [comment] 2015-11-25 14:53
more precisely, I think that you have a file without extension in your folder, and it's causing the problem

**Comment by trych** [comment] 2015-11-25 15:06
Hm, I can't confirm that, all my files have extensions.
Maybe it's the .DS_Store file that is present? But how can I even prevent that from being around (on OS X systems)? If that's causing the problem, is there any way to actively ignore that file during the execution of the script?

**Comment by fmassa** [comment] 2015-11-25 15:29
It's probably this file the guilty one.
I think something like this code snippet should be used instead of https://github.com/karpathy/neuraltalk2/blob/master/misc/DataLoaderRaw.lua#L33-L41
Could you replace those lines by this snippet and see if it works ?
```lua
local function isImage(f)
  for _,ext in pairs{'.jpg','.JPEG','.png'} do
    local _, end_idx =  f:find(ext)
    if end_idx and end_idx == f:len() then
      return true
    end
  end
  return false
end
for file in paths.files(opt.folder_path, isImage) do
  table.insert(self.files, fullpath)
  table.insert(self.ids, tostring(n)) -- just order them sequentially
  n=n+1
end
```

**Comment by trych** [comment] 2015-11-25 15:40
fmassa, thanks for looking into this. Does not work yet. Getting a different error this time:
```
$ th eval.lua -model /Users/username/Documents/NeuralTalk2/checkpoint_v1.t7_cpu.t7 -image_folder /Users/username/Documents/NeuralTalk2/Images -num_images 10 -gpuid -1
DataLoaderRaw loading images from folder:   /Users/username/Documents/NeuralTalk2/Images  
listing all images in directory /Users/username/Documents/NeuralTalk2/Images  
/Users/username/torch/install/bin/luajit: ./misc/DataLoaderRaw.lua:46: attempt to perform arithmetic on global 'n' (a nil value)
stack traceback:
  ./misc/DataLoaderRaw.lua:46: in function '__init'
  /Users/username/torch/install/share/lua/5.1/torch/init.lua:91: in function </Users/username/torch/install/share/lua/5.1/torch/init.lua:87>
  [C]: in function 'DataLoaderRaw'
  eval.lua:86: in main chunk
  [C]: in function 'dofile'
  ...username/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
  [C]: at 0x01024c8f10
```

**Comment by fmassa** [comment] 2015-11-25 15:41
I've updated my comment a few minutes ago, try it instead

**Comment by trych** [comment] 2015-11-25 15:48
This works. Great, thank you!
Should this issue be closed? I'm probably not the only one having this problem if it was the .DS_Store confusing the script.

**Comment by fmassa** [comment] 2015-11-25 15:49
I'll prepare a PR to fix it.

**Comment by trych** [comment] 2015-11-25 15:55
Perfect, thanks!

**Comment by fmassa** [comment] 2015-11-26 09:11
Fixed via https://github.com/karpathy/neuraltalk2/pull/12

**Comment by karpathy** [comment] 2015-11-26 17:33
Looks like the issue is fixed, closing. Thank you @trych for reporting and @fmassa for PR.

**Closed by karpathy** 2015-11-26 17:33 UTC
