### ISSUE TITLE
Out of memory training with 6G memory GPU

### ISSUE THREAD

**Issue by cudacaffe** [karpathy/neuraltalk2#8] opened 2015-11-24 19:53 UTC
Hi,

I got "out of memory" error when training with a Titan Z GPU which has 6GB memory:
th train.lua -input_h5 coco/cocotalk.h5 -input_json coco/cocotalk.json

The error messages are:
/blah/torch/install/bin/luajit: .../torch/install/share/lua/5.1/trepl/init.lua:363: /tmp/luarocks_cutorch-scm-1-8337/cutorch/lib/THC/THCTensorRandom.cu(20) : cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-8337/cutorch/lib/THC/THCGeneral.c:241
stack traceback:
        [C]: in function 'error'
        .../torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
        train.lua:79: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x00406670

I've tried reducing batch_size to 1 and also reducing rnn_size and input_encoding_size but none of
them helped.

Any idea what I may have missed? Many thanks.

**Comment by karpathy** [comment] 2015-11-24 20:36
hmmm, this shouldn't happen. It looks like you crash on "require cutorch", which is very very early in the code, before any of the model is even loaded. This seems to indicate some deeper problem with your setup and not something to do with the neuraltalk2 codebase.

**Comment by karpathy** [comment] 2015-11-26 17:37
It seems this issue was caused by `require 'cutorch'`, which indicates a general setup problem rather than an issue with neuraltalk2; closing. 

I hope you've resolved it! If not, happy to hear back and try to work it out.

**Closed by karpathy** 2015-11-26 17:37 UTC

**Comment by MozhdehDokhani** [comment] 2018-10-29 11:35
I have the same problem. @cudacaffe  How did you solve it?

P.S when I run it on CPU mode by passing the parameter -gpuid -1, it starts training. But I think it never ends!
